void solids_homogeneous_matrix ( void );
extern osg::Matrix MSol_Arm1_3D;
extern osg::Matrix MSol_Arm2_3D;
extern osg::Matrix MSol_Plane_3D;
extern osg::Matrix MSol_Disc_3D;
extern osg::Matrix MFra_FraARM1_draw;
extern osg::Matrix MFra_FraARM2_draw;
extern osg::Matrix MFra_FraDISC_draw;
extern osg::Matrix MFra_FraPLANE_draw;
extern osg::Matrix MFra_FraABS_draw;
