function C = C_(in1,in2,t,in4)
%C_
%    C = C_(IN1,IN2,T,IN4)

%    This function was generated by the Symbolic Math Toolbox version 5.7.
%    18-Apr-2016 12:49:32

R = in4(:,1);
c = in4(:,4);
C = reshape([c,-R.*c,-R.*c,R.^2.*c],[2, 2]);
