function delta = delta_(in1,in2,t,in4)
%DELTA_
%    DELTA = DELTA_(IN1,IN2,T,IN4)

%    This function was generated by the Symbolic Math Toolbox version 5.7.
%    18-Apr-2016 12:49:32

Fe = in4(:,5);
Me = in4(:,6);
delta = [Fe;Me];
