function K = K_(in1,in2,t,in4)
%K_
%    K = K_(IN1,IN2,T,IN4)

%    This function was generated by the Symbolic Math Toolbox version 5.7.
%    18-Apr-2016 12:49:32

K = reshape([0.0,0.0,0.0,0.0],[2, 2]);
