/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Fri Jun 28 13:03:36 2013
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void mu_div_mod_vel_sliding_vel_Outputs_wrapper(const real_T *u0,
                          const real_T *u1,
                          real_T *y0)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* This sample sets the output equal to the input
         y0[0] = u0[0];
For complex signals use: y0[0].re = u0[0].re;
                         y0[0].im = u0[0].im;
                         y1[0].re = u1[0].re;
                         y1[0].im = u1[0].im;*/

double a_w1 = 1.0;    double a_w2 = 0.54; 
double b_w1 = 4.01;   double b_w2 = 1.2;
double c_w1 = 0.7;    double c_w2 = 0.29; 
double d_w1 = 0.7;    double d_w2 = 0.29; 
double epsilon=0.0001;

double vel;
vel=3.6*u0[0]; /*covert m/s to km/h*/

if (u1[0]==1){
    
    if (fabs(vel)<=epsilon){
        y0[0]=(b_w1*d_w1)/exp(b_w1*fabs(vel)) - (a_w1*c_w1)/exp(a_w1*fabs(vel));
    }
    else{
         y0[0]=+(c_w1*exp(-a_w1*fabs(vel))-d_w1*exp(-b_w1*fabs(vel)))/fabs(u0[0]); 
    };
 
    
 
}
else{
    if (fabs(vel)<=epsilon){
        y0[0]=(b_w2*d_w2)/exp(b_w2*fabs(vel)) - (a_w2*c_w2)/exp(a_w2*fabs(vel));
    }
    else{
         y0[0]=+(c_w2*exp(-a_w2*fabs(vel))-d_w2*exp(-b_w2*fabs(vel)))/fabs(u0[0]); 
    };
 
};
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
