extern void osg_read_file ( void );
extern osg::Geode* axis;
extern osg::Geode* Fra_DFra_arm1_draw;
extern osg::Geode* Fra_DFra_arm2_draw;
extern osg::Geode* Fra_DFra_arm3_draw;
extern osg::Geode* Fra_FraABS_draw;
extern osg::Geode* Fra_FraABS2_draw;
extern osg::Geode* Vec_Varm1;
extern osg::Geode* Vec_Varm2;
extern osg::Geode* Vec_Varm3;
extern osg::Geode* Vec_Varm4;
extern osg::Geode* Vec_VOL2_OL3;
