void solids_homogeneous_matrix ( void );
extern osg::Matrix MFra_DFra_arm1_draw;
extern osg::Matrix MFra_DFra_arm2_draw;
extern osg::Matrix MFra_DFra_arm3_draw;
extern osg::Matrix MFra_FraABS_draw;
extern osg::Matrix MFra_FraABS2_draw;
extern osg::Matrix MVec_Varm1;
extern osg::Matrix MVec_Varm2;
extern osg::Matrix MVec_Varm3;
extern osg::Matrix MVec_Varm4;
extern osg::Matrix MVec_VOL2_OL3;
