#ifndef __linux__
  #include <windows.h>
#endif
 
#include <osg/Geode>
#include <osgDB/ReadFile>
 
osg::Geode* axis;
osg::Geode* Fra_FraR_WAG_draw;
osg::Geode* Fra_FraR_RBOG_draw;
osg::Geode* Fra_FraR_FBOG_draw;
osg::Geode* Fra_FraR_RAIL_draw;
osg::Geode* Fra_FraABS_draw;
osg::Geode* Fra_FraFWHSR_draw;
osg::Geode* Fra_FraFWHSF_draw;
osg::Geode* Fra_FraRWHSR_draw;
osg::Geode* Fra_FraRWHSF_draw;
osg::Geode* Sol_D_WAG;
osg::Geode* Sol_D_RBOG;
osg::Geode* Sol_D_RWHSF;
osg::Geode* Sol_D_RWHSR;
osg::Geode* Sol_D_RAXBFL;
osg::Geode* Sol_D_RAXBFR;
osg::Geode* Sol_D_RAXBRL;
osg::Geode* Sol_D_RAXBRR;
osg::Geode* Sol_D_RSLD;
osg::Geode* Sol_D_RMOTF;
osg::Geode* Sol_D_RMOTR;
osg::Geode* Sol_D_RROTF;
osg::Geode* Sol_D_RROTR;
osg::Geode* Sol_D_FBOG;
osg::Geode* Sol_D_FWHSF;
osg::Geode* Sol_D_FWHSR;
osg::Geode* Sol_D_FAXBFL;
osg::Geode* Sol_D_FAXBFR;
osg::Geode* Sol_D_FAXBRL;
osg::Geode* Sol_D_FAXBRR;
osg::Geode* Sol_D_FSLD;
osg::Geode* Sol_D_RAIL;
osg::Geode* Sol_D_RAXBFL1;
osg::Geode* Sol_D_RAXBFL2;
osg::Geode* Sol_D_RAXBFR1;
osg::Geode* Sol_D_RAXBFR2;
osg::Geode* Sol_D_RAXBRL1;
osg::Geode* Sol_D_RAXBRL2;
osg::Geode* Sol_D_RAXBRR1;
osg::Geode* Sol_D_RAXBRR2;
osg::Geode* Sol_D_RSUSPFL;
osg::Geode* Sol_D_RSUSPFR;
osg::Geode* Sol_D_RSUSPRL;
osg::Geode* Sol_D_RSUSPRR;
osg::Geode* Sol_D_RSUSPBEAML;
osg::Geode* Sol_D_RSUSPBEAMR;
osg::Geode* Sol_D_RSPRING2FL;
osg::Geode* Sol_D_RSPRING2RL;
osg::Geode* Sol_D_RSPRING2FR;
osg::Geode* Sol_D_RSPRING2RR;
osg::Geode* Sol_D_FAXBFL1;
osg::Geode* Sol_D_FAXBFL2;
osg::Geode* Sol_D_FAXBFR1;
osg::Geode* Sol_D_FAXBFR2;
osg::Geode* Sol_D_FAXBRL1;
osg::Geode* Sol_D_FAXBRL2;
osg::Geode* Sol_D_FAXBRR1;
osg::Geode* Sol_D_FAXBRR2;
osg::Geode* Sol_D_FSUSPFL;
osg::Geode* Sol_D_FSUSPFR;
osg::Geode* Sol_D_FSUSPRL;
osg::Geode* Sol_D_FSUSPRR;
osg::Geode* Sol_D_FSUSPBEAML;
osg::Geode* Sol_D_FSUSPBEAMR;
osg::Geode* Sol_D_FSPRING2FL;
osg::Geode* Sol_D_FSPRING2RL;
osg::Geode* Sol_D_FSPRING2FR;
osg::Geode* Sol_D_FSPRING2RR;
 
void osg_read_file ()
{
Fra_FraR_WAG_draw = (osg::Geode*) osgDB::readNodeFile("./axes.osg.[1.0].scale");
Fra_FraR_RBOG_draw = (osg::Geode*) osgDB::readNodeFile("./axes.osg.[0.5].scale");
Fra_FraR_FBOG_draw = (osg::Geode*) osgDB::readNodeFile("./axes.osg.[0.5].scale");
Fra_FraR_RAIL_draw = (osg::Geode*) osgDB::readNodeFile("./axes.osg.[0.5].scale");
Fra_FraABS_draw = (osg::Geode*) osgDB::readNodeFile("./axes.osg.[1].scale");
Fra_FraFWHSR_draw = (osg::Geode*) osgDB::readNodeFile("./axes.osg.[0.5].scale");
Fra_FraFWHSF_draw = (osg::Geode*) osgDB::readNodeFile("./axes.osg.[0.5].scale");
Fra_FraRWHSR_draw = (osg::Geode*) osgDB::readNodeFile("./axes.osg.[0.5100000000000000089].scale");
Fra_FraRWHSF_draw = (osg::Geode*) osgDB::readNodeFile("./axes.osg.[0.5].scale");
Sol_D_WAG = (osg::Geode*) osgDB::readNodeFile("./solids/wagon.stl.[1].scale");
Sol_D_RBOG = (osg::Geode*) osgDB::readNodeFile("./solids/bogie_m.stl.[1].scale");
Sol_D_RWHSF = (osg::Geode*) osgDB::readNodeFile("./solids/eje_m.stl.[1].scale");
Sol_D_RWHSR = (osg::Geode*) osgDB::readNodeFile("./solids/eje_m.stl.[1].scale");
Sol_D_RAXBFL = (osg::Geode*) osgDB::readNodeFile("./solids/axlebox_left_m.stl.[1].scale");
Sol_D_RAXBFR = (osg::Geode*) osgDB::readNodeFile("./solids/axlebox_rigth_m.stl.[1].scale");
Sol_D_RAXBRL = (osg::Geode*) osgDB::readNodeFile("./solids/axlebox_left_m.stl.[1].scale");
Sol_D_RAXBRR = (osg::Geode*) osgDB::readNodeFile("./solids/axlebox_rigth_m.stl.[1].scale");
Sol_D_RSLD = (osg::Geode*) osgDB::readNodeFile("./solids/slider.stl.[1].scale");
Sol_D_RMOTF = (osg::Geode*) osgDB::readNodeFile("./solids/carcasa_eje_motor_F.stl.[1].scale");
Sol_D_RMOTR = (osg::Geode*) osgDB::readNodeFile("./solids/carcasa_eje_motor_R.stl.[1].scale");
Sol_D_RROTF = (osg::Geode*) osgDB::readNodeFile("./solids/eje_motor_02.stl.[1].scale");
Sol_D_RROTR = (osg::Geode*) osgDB::readNodeFile("./solids/eje_motor_02.stl.[1].scale");
Sol_D_FBOG = (osg::Geode*) osgDB::readNodeFile("./solids/bogie_m.stl.[1].scale");
Sol_D_FWHSF = (osg::Geode*) osgDB::readNodeFile("./solids/eje_m.stl.[1].scale");
Sol_D_FWHSR = (osg::Geode*) osgDB::readNodeFile("./solids/eje_m.stl.[1].scale");
Sol_D_FAXBFL = (osg::Geode*) osgDB::readNodeFile("./solids/axlebox_left_m.stl.[1].scale");
Sol_D_FAXBFR = (osg::Geode*) osgDB::readNodeFile("./solids/axlebox_rigth_m.stl.[1].scale");
Sol_D_FAXBRL = (osg::Geode*) osgDB::readNodeFile("./solids/axlebox_left_m.stl.[1].scale");
Sol_D_FAXBRR = (osg::Geode*) osgDB::readNodeFile("./solids/axlebox_rigth_m.stl.[1].scale");
Sol_D_FSLD = (osg::Geode*) osgDB::readNodeFile("./solids/slider.stl.[1].scale");
Sol_D_RAIL = (osg::Geode*) osgDB::readNodeFile("./solids/rail_down_m.stl.[1].scale");
Sol_D_RAXBFL1 = (osg::Geode*) osgDB::readNodeFile("./solids/spring_m.stl.[1].scale");
Sol_D_RAXBFL2 = (osg::Geode*) osgDB::readNodeFile("./solids/spring_m.stl.[1].scale");
Sol_D_RAXBFR1 = (osg::Geode*) osgDB::readNodeFile("./solids/spring_m.stl.[1].scale");
Sol_D_RAXBFR2 = (osg::Geode*) osgDB::readNodeFile("./solids/spring_m.stl.[1].scale");
Sol_D_RAXBRL1 = (osg::Geode*) osgDB::readNodeFile("./solids/spring_m.stl.[1].scale");
Sol_D_RAXBRL2 = (osg::Geode*) osgDB::readNodeFile("./solids/spring_m.stl.[1].scale");
Sol_D_RAXBRR1 = (osg::Geode*) osgDB::readNodeFile("./solids/spring_m.stl.[1].scale");
Sol_D_RAXBRR2 = (osg::Geode*) osgDB::readNodeFile("./solids/spring_m.stl.[1].scale");
Sol_D_RSUSPFL = (osg::Geode*) osgDB::readNodeFile("./solids/suspender.stl.[1].scale");
Sol_D_RSUSPFR = (osg::Geode*) osgDB::readNodeFile("./solids/suspender.stl.[1].scale");
Sol_D_RSUSPRL = (osg::Geode*) osgDB::readNodeFile("./solids/suspender.stl.[1].scale");
Sol_D_RSUSPRR = (osg::Geode*) osgDB::readNodeFile("./solids/suspender.stl.[1].scale");
Sol_D_RSUSPBEAML = (osg::Geode*) osgDB::readNodeFile("./solids/suspender_beam.stl.[1].scale");
Sol_D_RSUSPBEAMR = (osg::Geode*) osgDB::readNodeFile("./solids/suspender_beam.stl.[1].scale");
Sol_D_RSPRING2FL = (osg::Geode*) osgDB::readNodeFile("./solids/spring2.stl.[1].scale");
Sol_D_RSPRING2RL = (osg::Geode*) osgDB::readNodeFile("./solids/spring2.stl.[1].scale");
Sol_D_RSPRING2FR = (osg::Geode*) osgDB::readNodeFile("./solids/spring2.stl.[1].scale");
Sol_D_RSPRING2RR = (osg::Geode*) osgDB::readNodeFile("./solids/spring2.stl.[1].scale");
Sol_D_FAXBFL1 = (osg::Geode*) osgDB::readNodeFile("./solids/spring_m.stl.[1].scale");
Sol_D_FAXBFL2 = (osg::Geode*) osgDB::readNodeFile("./solids/spring_m.stl.[1].scale");
Sol_D_FAXBFR1 = (osg::Geode*) osgDB::readNodeFile("./solids/spring_m.stl.[1].scale");
Sol_D_FAXBFR2 = (osg::Geode*) osgDB::readNodeFile("./solids/spring_m.stl.[1].scale");
Sol_D_FAXBRL1 = (osg::Geode*) osgDB::readNodeFile("./solids/spring_m.stl.[1].scale");
Sol_D_FAXBRL2 = (osg::Geode*) osgDB::readNodeFile("./solids/spring_m.stl.[1].scale");
Sol_D_FAXBRR1 = (osg::Geode*) osgDB::readNodeFile("./solids/spring_m.stl.[1].scale");
Sol_D_FAXBRR2 = (osg::Geode*) osgDB::readNodeFile("./solids/spring_m.stl.[1].scale");
Sol_D_FSUSPFL = (osg::Geode*) osgDB::readNodeFile("./solids/suspender.stl.[1].scale");
Sol_D_FSUSPFR = (osg::Geode*) osgDB::readNodeFile("./solids/suspender.stl.[1].scale");
Sol_D_FSUSPRL = (osg::Geode*) osgDB::readNodeFile("./solids/suspender.stl.[1].scale");
Sol_D_FSUSPRR = (osg::Geode*) osgDB::readNodeFile("./solids/suspender.stl.[1].scale");
Sol_D_FSUSPBEAML = (osg::Geode*) osgDB::readNodeFile("./solids/suspender_beam.stl.[1].scale");
Sol_D_FSUSPBEAMR = (osg::Geode*) osgDB::readNodeFile("./solids/suspender_beam.stl.[1].scale");
Sol_D_FSPRING2FL = (osg::Geode*) osgDB::readNodeFile("./solids/spring2.stl.[1].scale");
Sol_D_FSPRING2RL = (osg::Geode*) osgDB::readNodeFile("./solids/spring2.stl.[1].scale");
Sol_D_FSPRING2FR = (osg::Geode*) osgDB::readNodeFile("./solids/spring2.stl.[1].scale");
Sol_D_FSPRING2RR = (osg::Geode*) osgDB::readNodeFile("./solids/spring2.stl.[1].scale");
}
